package org.immregistries.dqa.validator.engine.issues;

import org.immregistries.dqa.codebase.client.reference.CodesetType;

public enum IssueField {
			  GENERAL_AUTHORIZATION("authorization", null)
			, GENERAL_CONFIGURATION("configuration", null)
			, GENERAL_PARSE("parse", null)
			, GENERAL_PROCESSING("processing", null)
			, HL7_SEGMENT("segment", null)
			, HL7_SEGMENTS("segments", null)
			, HL7_MSH_ACCEPT_ACK_TYPE("accept ack type", null)
			, HL7_MSH_ALT_CHARACTER_SET("alt character set", null)
			, HL7_MSH_APP_ACK_TYPE("app ack type", null)
			, HL7_MSH_CHARACTER_SET("character set", null)
			, HL7_MSH_COUNTRY_CODE("country code", null)
			, HL7_MSH_ENCODING_CHARACTER("encoding character", null)
			, HL7_MSH_MESSAGE_CONTROL_ID("message control id", null)
			, HL7_MSH_MESSAGE_DATE("message date", null)
			, HL7_MSH_MESSAGE_PROFILE_ID("message profile id", null)
			, HL7_MSH_MESSAGE_STRUCTURE("message structure", null)
			, HL7_MSH_MESSAGE_TRIGGER("message trigger", null)
			, HL7_MSH_MESSAGE_TYPE("message type", null)
			, HL7_MSH_PROCESSING_ID("processing id", null)
			, HL7_MSH_RECEIVING_APPLICATION("receiving application", null)
			, HL7_MSH_RECEIVING_FACILITY("receiving facility", null)
			, HL7_MSH_SEGMENT("segment", null)
			, HL7_MSH_SENDING_APPLICATION("sending application", null)
			, HL7_MSH_SENDING_FACILITY("sending facility", null)
			, HL7_MSH_VERSION("version", null)
			, HL7_NK1_SEGMENT("segment", null)
			, HL7_NK1_SET_ID("set id", null)
			, HL7_OBX_SEGMENT("segment", null)
			, HL7_ORC_SEGMENT("segment", null)
			, HL7_PD1_SEGMENT("segment", null)
			, HL7_PID_SEGMENT("segment", null)
			, HL7_PV1_SEGMENT("segment", null)
			, HL7_RXA_ADMIN_SUB_ID_COUNTER("admin sub id counter", null)
			, HL7_RXA_GIVE_SUB_ID("give sub id", null)
			, HL7_RXA_SEGMENT("segment", null)
			, HL7_RXR_SEGMENT("segment", null)
			
			, NEXT_OF_KIN_ADDRESS("address", null)
			, NEXT_OF_KIN_ADDRESS_CITY("address city", null)
			, NEXT_OF_KIN_ADDRESS_COUNTRY("address country", null)
			, NEXT_OF_KIN_ADDRESS_COUNTY("address county", null)
			, NEXT_OF_KIN_ADDRESS_STATE("address state", null)
			, NEXT_OF_KIN_ADDRESS_STREET("address street", null)
			, NEXT_OF_KIN_ADDRESS_STREET2("address street2", null)
			, NEXT_OF_KIN_ADDRESS_TYPE("address type", null)
			, NEXT_OF_KIN_ADDRESS_ZIP("address zip", null)
			, NEXT_OF_KIN_NAME("name", null)
			, NEXT_OF_KIN_NAME_FIRST("name first", null)
			, NEXT_OF_KIN_NAME_LAST("name last", null)
			, NEXT_OF_KIN_PHONE_NUMBER("phone number", null)
			, NEXT_OF_KIN_RELATIONSHIP("relationship", null)
			, NEXT_OF_KIN_SSN("SSN", null)
			, OBSERVATION_VALUE_TYPE("value type", CodesetType.HL7_VALUE_TYPE)
			, OBSERVATION_IDENTIFIER_CODE("identifier code", null)
			, OBSERVATION_VALUE("value", null)
			, OBSERVATION_DATE_TIME_OF_OBSERVATION("date time of observation", null)
			, PATIENT_ADDRESS("address", null)
			, PATIENT_ADDRESS_CITY("address city", null)
			, PATIENT_ADDRESS_COUNTRY("address country", null)
			, PATIENT_ADDRESS_COUNTY("address county", null)
			, PATIENT_ADDRESS_STATE("address state", null)
			, PATIENT_ADDRESS_STREET("address street", null)
			, PATIENT_ADDRESS_STREET2("address street2", null)
			, PATIENT_ADDRESS_TYPE("address type", null)
			, PATIENT_ADDRESS_ZIP("address zip", null)
			, PATIENT_ALIAS("alias", null)
			, PATIENT_BIRTH_DATE("birth date", null)
			, PATIENT_BIRTH_INDICATOR("birth indicator", null)
			, PATIENT_BIRTH_ORDER("birth order", CodesetType.BIRTH_ORDER)
			, PATIENT_BIRTH_PLACE("birth place", null)
			, PATIENT_BIRTH_REGISTRY_ID("birth registry id", null)
			, PATIENT_CLASS("class", null)
			, PATIENT_DEATH_DATE("death date", null)
			, PATIENT_DEATH_INDICATOR("death indicator", null)
			, PATIENT_ETHNICITY("ethnicity", CodesetType.PATIENT_ETHNICITY)
			, PATIENT_GENDER("gender", CodesetType.PATIENT_SEX)
			, PATIENT_GUARDIAN_ADDRESS("guardian address", null)
			, PATIENT_GUARDIAN_ADDRESS_CITY("guardian address city", null)
			, PATIENT_GUARDIAN_ADDRESS_STATE("guardian address state", null)
			, PATIENT_GUARDIAN_ADDRESS_STREET("guardian address street", null)
			, PATIENT_GUARDIAN_ADDRESS_ZIP("guardian address zip", null)
			, PATIENT_GUARDIAN_NAME("guardian name", null)
			, PATIENT_GUARDIAN_NAME_FIRST("guardian name first", null)
			, PATIENT_GUARDIAN_NAME_LAST("guardian name last", null)
			, PATIENT_GUARDIAN_RESPONSIBLE_PARTY("guardian responsible party", null)
			, PATIENT_GUARDIAN_PHONE("guardian phone", null)
			, PATIENT_GUARDIAN_RELATIONSHIP("guardian relationship", null)
			, PATIENT_IMMUNITY_CODE("immunity code", CodesetType.EVIDENCE_OF_IMMUNITY)
			, PATIENT_IMMUNIZATION_REGISTRY_STATUS("immunization registry status", null)
			, PATIENT_MEDICAID_NUMBER("Medicaid number", null)
			, PATIENT_MIDDLE_NAME("middle name", null)
			, PATIENT_MOTHERS_MAIDEN_NAME("mother's maiden name", null)
			, PATIENT_NAME("name", null)
			, PATIENT_NAME_FIRST("name first", null)
			, PATIENT_NAME_LAST("name last", null)
			, PATIENT_NAME_TYPE_CODE("name type code", CodesetType.PERSON_NAME_TYPE)
			, PATIENT_PHONE("phone", null)
			, PATIENT_PHONE_TEL_USE_CODE("phone tel use code", null)
			, PATIENT_PHONE_TEL_EQUIP_CODE("phone tel equip code", null)
			, PATIENT_PRIMARY_FACILITY_ID("primary facility id", null)
			, PATIENT_PRIMARY_FACILITY_NAME("primary facility name", null)
			, PATIENT_PRIMARY_LANGUAGE("primary language", CodesetType.PERSON_LANGUAGE)
			, PATIENT_PRIMARY_PHYSICIAN_ID("primary physician id", CodesetType.PHYSICIAN_NUMBER)
			, PATIENT_PRIMARY_PHYSICIAN_NAME("primary physician name", null)
			, PATIENT_PROTECTION_INDICATOR("protection indicator", CodesetType.PATIENT_PROTECTION)
			, PATIENT_PUBLICITY_CODE("publicity code", CodesetType.PATIENT_PUBLICITY)
			, PATIENT_RACE("race", CodesetType.PATIENT_RACE)
			, PATIENT_REGISTRY_ID("registry id", null)
			, PATIENT_REGISTRY_STATUS("registry status", null)
			, PATIENT_SSN("SSN", null)
			, PATIENT_SUBMITTER_ID("submitter id", null)
			, PATIENT_SUBMITTER_ID_AUTHORITY("submitter id authority", null)
			, PATIENT_SUBMITTER_ID_TYPE_CODE("submitter id type code", null)
			, PATIENT_SYSTEM_CREATION_DATE("system creation date", null)
			, PATIENT_VFC_EFFECTIVE_DATE("VFC effective date", null)
			, PATIENT_VFC_STATUS("VFC status", CodesetType.FINANCIAL_STATUS_CODE)
			, PATIENT_WIC_ID("WIC id", null)
			, VACCINATION_ACTION_CODE("action code", null)
			, VACCINATION_ADMIN_CODE("admin code", CodesetType.VACCINATION_CVX_CODE)
			, VACCINATION_ADMIN_CODE_TABLE("admin code table", null)
			, VACCINATION_ADMIN_DATE("admin date", null)
			, VACCINATION_ADMIN_DATE_END("admin date end", null)
			, VACCINATION_ADMINISTERED_AMOUNT("administered amount", null)
			, VACCINATION_ADMINISTERED_UNIT("administered unit", null)
			, VACCINATION_BODY_ROUTE("body route", null)
			, VACCINATION_BODY_SITE("body site", null)
			, VACCINATION_COMPLETION_STATUS("completion status", null)
			, VACCINATION_CONFIDENTIALITY_CODE("confidentiality code", null)
			, VACCINATION_CPT_CODE("CPT code", CodesetType.VACCINATION_CPT_CODE)
			, VACCINATION_CVX_CODE("CVX code", null)
			, VACCINATION_CVX_CODE_AND_CPT_CODE("CVX code and CPT code", null)
			, VACCINATION_FACILITY_ID("facility id", null)
			, VACCINATION_FACILITY_NAME("facility name", null)
			, VACCINATION_FACILITY_TYPE("facility type", null)
			, VACCINATION_FILLER_ORDER_NUMBER("filler order number", null)
			, VACCINATION_FINANCIAL_ELIGIBILITY_CODE("financial eligibility code", null)
			, VACCINATION_GIVEN_BY("given by", null)
			, VACCINATION_ID("id", null)
			, VACCINATION_ID_OF_RECEIVER("id of receiver", null)
			, VACCINATION_ID_OF_SENDER("id of sender", null)
			, VACCINATION_INFORMATION_SOURCE("information source", null)
			, VACCINATION_VIS("VIS", null)
			, VACCINATION_VIS_CVX_CODE("VIS CVX Code", CodesetType.VACCINATION_VIS_CVX_CODE)
			, VACCINATION_VIS_DOCUMENT_TYPE("VIS document type", null)
			, VACCINATION_VIS_PUBLISHED_DATE("VIS published date", null)
			, VACCINATION_VIS_PRESENTED_DATE("VIS presented date", null)
			, VACCINATION_LOT_EXPIRATION_DATE("lot expiration date", null)
			, VACCINATION_LOT_NUMBER("lot number", null)
			, VACCINATION_MANUFACTURER_CODE("manufacturer code", CodesetType.VACCINATION_MANUFACTURER_CODE)
			, VACCINATION_ORDER_CONTROL_CODE("order control code", null)
			, VACCINATION_ORDER_FACILITY_ID("order facility id", null)
			, VACCINATION_ORDER_FACILITY_NAME("order facility name", null)
			, VACCINATION_ORDERED_BY("ordered by", null)
			, VACCINATION_PLACER_ORDER_NUMBER("placer order number", null)
			, VACCINATION_PRODUCT("product", CodesetType.VACCINE_PRODUCT)
			, VACCINATION_RECORDED_BY("recorded by", null)
			, VACCINATION_REFUSAL_REASON("refusal reason", CodesetType.VACCINATION_REFUSAL)
			, VACCINATION_SYSTEM_ENTRY_TIME("system entry time", null)
			, VACCINATION_TRADE_NAME("trade name", null)
			, VACCINATION_TRADE_NAME_AND_VACCINE("trade name and vaccine", null)
			, VACCINATION_TRADE_NAME_AND_MANUFACTURER("trade name and manufacturer", null)
			, VACCINATION_VALIDITY_CODE("validity code", null)
			, NONE("object", null)
			;
	
		private final String fieldDescription;
		private final CodesetType valueType;
		
		private IssueField(String fieldDesc, CodesetType typeOfValue) {
			this.fieldDescription = fieldDesc;
			this.valueType = typeOfValue;
		}
		
		public String getFieldDescription() {
			return fieldDescription;
		}

		public CodesetType getCodesetType() {
			return valueType;
		}

}
