package com.openimmunizationsoftware.dqa.validator.issues;

public enum IssueField {
	GENERAL_AUTHORIZATION("authorization")
			, GENERAL_CONFIGURATION("configuration")
			, GENERAL_PARSE("parse")
			, GENERAL_PROCESSING("processing")
			, HL7_SEGMENT("segment")
			, HL7_SEGMENTS("segments")
			, HL7_MSH_ACCEPT_ACK_TYPE("accept ack type")
			, HL7_MSH_ALT_CHARACTER_SET("alt character set")
			, HL7_MSH_APP_ACK_TYPE("app ack type")
			, HL7_MSH_CHARACTER_SET("character set")
			, HL7_MSH_COUNTRY_CODE("country code")
			, HL7_MSH_ENCODING_CHARACTER("encoding character")
			, HL7_MSH_MESSAGE_CONTROL_ID("message control id")
			, HL7_MSH_MESSAGE_DATE("message date")
			, HL7_MSH_MESSAGE_PROFILE_ID("message profile id")
			, HL7_MSH_MESSAGE_STRUCTURE("message structure")
			, HL7_MSH_MESSAGE_TRIGGER("message trigger")
			, HL7_MSH_MESSAGE_TYPE("message type")
			, HL7_MSH_PROCESSING_ID("processing id")
			, HL7_MSH_RECEIVING_APPLICATION("receiving application")
			, HL7_MSH_RECEIVING_FACILITY("receiving facility")
			, HL7_MSH_SEGMENT("segment")
			, HL7_MSH_SENDING_APPLICATION("sending application")
			, HL7_MSH_SENDING_FACILITY("sending facility")
			, HL7_MSH_VERSION("version")
			, HL7_NK1_SEGMENT("segment")
			, HL7_NK1_SET_ID("set id")
			, HL7_OBX_SEGMENT("segment")
			, HL7_ORC_SEGMENT("segment")
			, HL7_PD1_SEGMENT("segment")
			, HL7_PID_SEGMENT("segment")
			, HL7_PV1_SEGMENT("segment")
			, HL7_RXA_ADMIN_SUB_ID_COUNTER("admin sub id counter")
			, HL7_RXA_GIVE_SUB_ID("give sub id")
			, HL7_RXA_SEGMENT("segment")
			, HL7_RXR_SEGMENT("segment")
			, NEXT_OF_KIN_ADDRESS("address")
			, NEXT_OF_KIN_ADDRESS_CITY("address city")
			, NEXT_OF_KIN_ADDRESS_COUNTRY("address country")
			, NEXT_OF_KIN_ADDRESS_COUNTY("address county")
			, NEXT_OF_KIN_ADDRESS_STATE("address state")
			, NEXT_OF_KIN_ADDRESS_STREET("address street")
			, NEXT_OF_KIN_ADDRESS_STREET2("address street2")
			, NEXT_OF_KIN_ADDRESS_TYPE("address type")
			, NEXT_OF_KIN_ADDRESS_ZIP("address zip")
			, NEXT_OF_KIN_NAME("name")
			, NEXT_OF_KIN_NAME_FIRST("name first")
			, NEXT_OF_KIN_NAME_LAST("name last")
			, NEXT_OF_KIN_PHONE_NUMBER("phone number")
			, NEXT_OF_KIN_RELATIONSHIP("relationship")
			, NEXT_OF_KIN_SSN("SSN")
			, OBSERVATION_VALUE_TYPE("value type")
			, OBSERVATION_IDENTIFIER_CODE("identifier code")
			, OBSERVATION_VALUE("value")
			, OBSERVATION_DATE_TIME_OF_OBSERVATION("date time of observation")
			, PATIENT_ADDRESS("address")
			, PATIENT_ADDRESS_CITY("address city")
			, PATIENT_ADDRESS_COUNTRY("address country")
			, PATIENT_ADDRESS_COUNTY("address county")
			, PATIENT_ADDRESS_STATE("address state")
			, PATIENT_ADDRESS_STREET("address street")
			, PATIENT_ADDRESS_STREET2("address street2")
			, PATIENT_ADDRESS_TYPE("address type")
			, PATIENT_ADDRESS_ZIP("address zip")
			, PATIENT_ALIAS("alias")
			, PATIENT_BIRTH_DATE("birth date")
			, PATIENT_BIRTH_INDICATOR("birth indicator")
			, PATIENT_BIRTH_ORDER("birth order")
			, PATIENT_BIRTH_PLACE("birth place")
			, PATIENT_BIRTH_REGISTRY_ID("birth registry id")
			, PATIENT_CLASS("class")
			, PATIENT_DEATH_DATE("death date")
			, PATIENT_DEATH_INDICATOR("death indicator")
			, PATIENT_ETHNICITY("ethnicity")
			, PATIENT_GENDER("gender")
			, PATIENT_GUARDIAN_ADDRESS("guardian address")
			, PATIENT_GUARDIAN_ADDRESS_CITY("guardian address city")
			, PATIENT_GUARDIAN_ADDRESS_STATE("guardian address state")
			, PATIENT_GUARDIAN_ADDRESS_STREET("guardian address street")
			, PATIENT_GUARDIAN_ADDRESS_ZIP("guardian address zip")
			, PATIENT_GUARDIAN_NAME("guardian name")
			, PATIENT_GUARDIAN_NAME_FIRST("guardian name first")
			, PATIENT_GUARDIAN_NAME_LAST("guardian name last")
			, PATIENT_GUARDIAN_RESPONSIBLE_PARTY("guardian responsible party")
			, PATIENT_GUARDIAN_PHONE("guardian phone")
			, PATIENT_GUARDIAN_RELATIONSHIP("guardian relationship")
			, PATIENT_IMMUNITY_CODE("immunity code")
			, PATIENT_IMMUNIZATION_REGISTRY_STATUS("immunization registry status")
			, PATIENT_MEDICAID_NUMBER("Medicaid number")
			, PATIENT_MIDDLE_NAME("middle name")
			, PATIENT_MOTHERS_MAIDEN_NAME("mother's maiden name")
			, PATIENT_NAME("name")
			, PATIENT_NAME_FIRST("name first")
			, PATIENT_NAME_LAST("name last")
			, PATIENT_NAME_TYPE_CODE("name type code")
			, PATIENT_PHONE("phone")
			, PATIENT_PHONE_TEL_USE_CODE("phone tel use code")
			, PATIENT_PHONE_TEL_EQUIP_CODE("phone tel equip code")
			, PATIENT_PRIMARY_FACILITY_ID("primary facility id")
			, PATIENT_PRIMARY_FACILITY_NAME("primary facility name")
			, PATIENT_PRIMARY_LANGUAGE("primary language")
			, PATIENT_PRIMARY_PHYSICIAN_ID("primary physician id")
			, PATIENT_PRIMARY_PHYSICIAN_NAME("primary physician name")
			, PATIENT_PROTECTION_INDICATOR("protection indicator")
			, PATIENT_PUBLICITY_CODE("publicity code")
			, PATIENT_RACE("race")
			, PATIENT_REGISTRY_ID("registry id")
			, PATIENT_REGISTRY_STATUS("registry status")
			, PATIENT_SSN("SSN")
			, PATIENT_SUBMITTER_ID("submitter id")
			, PATIENT_SUBMITTER_ID_AUTHORITY("submitter id authority")
			, PATIENT_SUBMITTER_ID_TYPE_CODE("submitter id type code")
			, PATIENT_SYSTEM_CREATION_DATE("system creation date")
			, PATIENT_VFC_EFFECTIVE_DATE("VFC effective date")
			, PATIENT_VFC_STATUS("VFC status")
			, PATIENT_WIC_ID("WIC id")
			, VACCINATION_ACTION_CODE("action code")
			, VACCINATION_ADMIN_CODE("admin code")
			, VACCINATION_ADMIN_CODE_TABLE("admin code table")
			, VACCINATION_ADMIN_DATE("admin date")
			, VACCINATION_ADMIN_DATE_END("admin date end")
			, VACCINATION_ADMINISTERED_AMOUNT("administered amount")
			, VACCINATION_ADMINISTERED_UNIT("administered unit")
			, VACCINATION_BODY_ROUTE("body route")
			, VACCINATION_BODY_SITE("body site")
			, VACCINATION_COMPLETION_STATUS("completion status")
			, VACCINATION_CONFIDENTIALITY_CODE("confidentiality code")
			, VACCINATION_CPT_CODE("CPT code")
			, VACCINATION_CVX_CODE("CVX code")
			, VACCINATION_CVX_CODE_AND_CPT_CODE("CVX code and CPT code")
			, VACCINATION_FACILITY_ID("facility id")
			, VACCINATION_FACILITY_NAME("facility name")
			, VACCINATION_FACILITY_TYPE("facility type")
			, VACCINATION_FILLER_ORDER_NUMBER("filler order number")
			, VACCINATION_FINANCIAL_ELIGIBILITY_CODE("financial eligibility code")
			, VACCINATION_GIVEN_BY("given by")
			, VACCINATION_ID("id")
			, VACCINATION_ID_OF_RECEIVER("id of receiver")
			, VACCINATION_ID_OF_SENDER("id of sender")
			, VACCINATION_INFORMATION_SOURCE("information source")
			, VACCINATION_VIS("VIS")
			, VACCINATION_VIS_CVX_CODE("VIS CVX Code")
			, VACCINATION_VIS_DOCUMENT_TYPE("VIS document type")
			, VACCINATION_VIS_PUBLISHED_DATE("VIS published date")
			, VACCINATION_VIS_PRESENTED_DATE("VIS presented date")
			, VACCINATION_LOT_EXPIRATION_DATE("lot expiration date")
			, VACCINATION_LOT_NUMBER("lot number")
			, VACCINATION_MANUFACTURER_CODE("manufacturer code")
			, VACCINATION_ORDER_CONTROL_CODE("order control code")
			, VACCINATION_ORDER_FACILITY_ID("order facility id")
			, VACCINATION_ORDER_FACILITY_NAME("order facility name")
			, VACCINATION_ORDERED_BY("ordered by")
			, VACCINATION_PLACER_ORDER_NUMBER("placer order number")
			, VACCINATION_PRODUCT("product")
			, VACCINATION_RECORDED_BY("recorded by")
			, VACCINATION_REFUSAL_REASON("refusal reason")
			, VACCINATION_SYSTEM_ENTRY_TIME("system entry time")
			, VACCINATION_TRADE_NAME("trade name")
			, VACCINATION_TRADE_NAME_AND_VACCINE("trade name and vaccine")
			, VACCINATION_TRADE_NAME_AND_MANUFACTURER("trade name and manufacturer")
			, VACCINATION_VALIDITY_CODE("validity code")
			, NONE("object")
			;
	
		private String fieldDescription;
		private IssueField(String fieldDesc) {
			this.fieldDescription = fieldDesc;
			
		}
		public String getFieldDescription() {
			return fieldDescription;
		}
		
		
}
